version: "3.8"


services:
    manytask:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: manytask
        env_file: .env
        environment:
            FLASK_ENV: development
            CACHE_DIR: /cache
        ports:
            - "5000:5000"
        volumes:
            - /cache